### ISSUE TITLE
Reinforcement_Learning/ch8-trajectory_sampling.ipynb not quite right

### ISSUE THREAD

**Issue by MaraTomasek** [MarcTomasek/ML-Notebooks#1]
Uniform- and trajectory-sampling should be easier to distinguish in plots,
where uniform has a slower start but better values later on.

This is _only_ cleary visible in the case where we only have one branch.

**Comment by capymarato** [comment]
I decided that it was ok this way,
based on other similar plots being heavily averaged to get smoother lines.
